---


- name: "Be sure libselinux-python are ime=nstalled to avoid errors"
  yum: name=libselinux-python state=present

- name: "Disable iptables"
  service: name=iptables enabled=no state=stopped
  ignore_errors: True

- name: "Disable iptables"
  service: name=iptables enabled=no state=stopped

- name: "Disable ip6tables"
  service: name=ip6tables enabled=no state=stopped

- name: "Ensure US keyboard"
  copy: src=etc/grub.conf dest=/etc/grub.conf

- name: "Ensure US keybindings"
  lineinfile: dest=/etc/sysconfig/i18n regexp="de_DE" line='LANG="en_US.UTF-8"'

- name: "Ensure US keybindings part 2"
  lineinfile: dest=/etc/sysconfig/keyboard regexp="de" line='KEYTABLE="us"'

#- name: "Minimize Swapping with swappiness=1"
#  sysctl: name=vm.swappiness value=1 state=present reload=yes
#  ignore_errors: True

- name: "Install EPEL repo"
  yum: name=http://mirror.nexcess.net/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present

- name: "Install glibc-common"
  yum: name="glibc-common" state=latest

#- name: "Set locale to US"
#  locale_gen: name=LANG=en_US.UTF-8 state=present

- name: "Add fonts"
  yum: name='@Fonts' state=present

- name: "Add gui"
  yum: name='@X Window System' state=present

- name: "Add desktop"
  yum: name='@KDE desktop' state=present

- name: "Install firefox"
  yum: name="firefox" state=latest

- name: "Install wget"
  yum: name="wget" state=latest

- name: "Install vim"
  yum: name="vim" state=latest

- name: "Install emacs"
  yum: name=emacs state=latest

- name: "Install nano"
  yum: name="nano" state=latest

- name: "Install vim"
  yum: name="emacs" state=latest

- name: "Install build tools"
  yum: name="@Development tools" state=latest

- name: "Install tmux ( epel )"
  yum: name="tmux" state=latest

- name: "Install openssl"
  yum: name="openssl" state=latest

#- name: "Update all to latest o_O"
#  yum: name=* state=latest


