---

- name: "Add Ambari Repo"
  copy: src=etc/yum.repos.d/ambari.repo
        dest=/etc/yum.repos.d/ambari.repo
        owner=root
        group=root
        mode=0644

- name: "check postgresql db installed"
  shell: "rpm -qa postgresql && echo Installed || echo Missing"
  register: postgresql_installed

- name: "Add Ambari Repo key"
  command: "rpm --import http://public-repo-1.hortonworks.com/ambari/centos6/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins"

- name: "Install Ambari Manager Server"
  yum: name=ambari-server state=present

- name: "Initialize postgresql db"
  shell: "/sbin/service postgresql initdb"
  args:
        creates: /usr/share/pgsql/.db_init

- name: "Start Ambari Manager postgresql DB"
  service: name=postgresql state=started

- name: "Start Ambari Manager postgresql DB"
  service: name=postgresql state=started

- name: "Run Ambari Server setup"
  shell: /usr/sbin/ambari-server setup -s

- name: "Enable the ambari-server service"
  service: name=ambari-server state=restarted enabled=yes

- name: "Waiting for ambari-server to start listening on port 8080"
  wait_for: host=127.0.0.1 port=8080

- name: "Waiting for ambari-agents to register"
  uri: url=http://127.0.0.1:8080/api/v1/hosts/hostvars[item]['127.0.0.1'] }}
       method=GET
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       status_code=200,201,202,404
  with_items: groups['hadoop-cluster']
  register: result
  until: "result.status != 404"
  retries: 200
  delay: 5


