---

- name: "Check for java 7"
  shell: "/usr/java/latest/bin/java -version 2>&1 | fgrep -q '1.7.0_75' && echo Installed || echo Missing"
  register: java7installed

- name: "Copy java installer to /tmp"
  copy: src=jdk-7u75-linux-x64.rpm dest=/tmp/jdk-7u75-linux-x64.rpm
  when: java7installed.stdout == 'Missing'

- name: "Install java 1.7"
  script: install-java7.sh
  when: java7installed.stdout == 'Missing'

- name: "Update java alternatives to /usr/java/latest"
  command: /usr/sbin/alternatives --install /usr/bin/java java /usr/java/latest/jre/bin/java 20000

- name: "Add JAVA_HOME to env"
  copy: src=etc/profile.d/java.sh dest=/etc/profile.d/java.sh owner=root group=root mode=0644

- name: "Create /opt/maven"
  file: path=/opt/maven state=directory

- name: "Download maven"
  copy: src=opt/maven/apache-maven-3.1.1-bin.tar.gz dest=/opt/maven/apache-maven-3.1.1-bin.tar.gz

- name: "Install maven"
  command: tar -zxf /opt/maven/apache-maven-3.1.1-bin.tar.gz -C /opt/maven

- name: "Maven symlink"
  file: src=/opt/maven/apache-maven-3.1.1 dest=/opt/maven/current state=link

- name: "Add maven to path"
  copy: src=etc/profile.d/maven.sh dest=/etc/profile.d/maven.sh owner=root group=root mode=0644

